export interface User {
  id: string; // UUID from Supabase auth
  email: string;
  name: string;
  avatarUrl?: string;
  createdAt: string;
  updatedAt?: string;
  language?: string; // Language preference (e.g., 'en', 'es', 'fr', 'ta')
}

export interface UserSettings {
  userId: string;
  language: string; // ISO language code
  createdAt: string;
  updatedAt: string;
}

export interface Folder {
  id: string; // UUID generated by Supabase
  userId: string;
  name: string;
  color: 'amber' | 'orange' | 'emerald';
  videoCount?: number; // Computed field
  createdAt: string;
  updatedAt: string;
}

export interface Video {
  id: string;
  userId: string;
  folderId: string | null; // Can be null if not in a folder
  youtubeUrl: string;
  videoId: string;
  title: string;
  thumbnail: string | null;
  summary: string | null;
  notes: string[];
  duration: string | null;
  watched: boolean;
  flashcardsCount?: number;
  isExisting?: boolean;
  transcript?: {
    original: string;
    originalLanguage: string;
    english: string;
  };
  createdAt: string;
  updatedAt: string;
}

export interface Flashcard {
  id: string;
  videoId: string;
  question: string;
  answer: string;
  mastered: boolean;
  lastReviewed?: string;
  createdAt: string;
  updatedAt: string;
}

export interface ProcessingStatus {
  id: string;
  videoId: string;
  userId: string;
  stage: 'idle' | 'extracting' | 'generating'| 'complete' | 'error';
  message: string | null;
  progress: number;
  error: string | null;
  createdAt: string;
  updatedAt: string;
}

export type CourseLevel = 'Beginner' | 'Intermediate' | 'Advanced';

export type CourseGoal =
  | 'Placements'
  | 'Competitive Programming'
  | 'Concepts'
  | 'Interview Prep';

export interface CourseGeneratorInput {
  topic: string;
  programmingLanguage?: string;
}

export interface CourseVideoItem {
  title: string;
  educator?: string;
  url?: string;
}

export interface CourseModuleQuiz {
  question: string;
  options: string[];
  correctAnswer: string;
  explanation?: string;
  sourceVideoTitle?: string;
}

export interface CourseModule {
  id: string;
  name: string;
  conceptsCovered: string[];
  difficultyLevel: string;
  expectedOutcome: string;
  videos: CourseVideoItem[];
  quizzes: CourseModuleQuiz[];
}

export interface CourseCheckpoint {
  title: string;
  afterModule: number;
  quizTopics: string[];
  practiceSuggestions: string[];
}

export interface CourseTrackingDefinition {
  completionPercent: number;
  completedModules: number;
  totalModules: number;
  quizScores: number[];
}

export interface GeneratedCoursePlan {
  id: string;
  title: string;
  overview: string;
  modules: CourseModule[];
  checkpoints: CourseCheckpoint[];
  tracking: CourseTrackingDefinition;
  finalOutcome: string;
}

