export interface User {
  id: string; // UUID from Supabase auth
  email: string;
  name: string;
  avatarUrl?: string;
  createdAt: string;
  updatedAt?: string;
}

export interface Folder {
  id: string; // UUID generated by Supabase
  userId: string;
  name: string;
  color: 'amber' | 'orange' | 'emerald';
  videoCount?: number; // Computed field
  createdAt: string;
  updatedAt: string;
}

export interface Video {
  id: string;
  userId: string;
  folderId: string | null; // Can be null if not in a folder
  youtubeUrl: string;
  videoId: string;
  title: string;
  thumbnail: string | null;
  summary: string | null;
  notes: string[];
  duration: string | null;
  watched: boolean;
  flashcardsCount?: number;
  isExisting?: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface Flashcard {
  id: string;
  videoId: string;
  question: string;
  answer: string;
  mastered: boolean;
  lastReviewed?: string;
  createdAt: string;
  updatedAt: string;
}

export interface ProcessingStatus {
  id: string;
  videoId: string;
  userId: string;
  stage: 'idle' | 'extracting' | 'generating'| 'complete' | 'error';
  message: string | null;
  progress: number;
  error: string | null;
  createdAt: string;
  updatedAt: string;
}

